### ISSUE TITLE
Error with predict.py

### ISSUE THREAD

**Issue by permanent26** [haofeixu/aanet#21]
(aanet) permanent@permanent-G3-3579:~/aanet-master$ CUDA_VISIBLE_DEVICES=0 python predict.py --data_dir demo --pretrained_aanet pretrained/aanet+_kitti15-2075aea1.pth
=> Loading pretrained AANet: pretrained/aanet+_kitti15-2075aea1.pth
=> 1 samples found in the data dir
=> Inferencing 0/1
Traceback (most recent call last):
  File "predict.py", line 195, in <module>
    main()
  File "predict.py", line 161, in main
    pred_disp = aanet(left, right)[-1]  # [B, H, W]
  File "/home/permanent/anaconda3/envs/aanet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/permanent/aanet-master/nets/aanet.py", line 207, in forward
    left_feature = self.feature_extraction(left_img)
  File "/home/permanent/aanet-master/nets/aanet.py", line 134, in feature_extraction
    feature = self.feature_extractor(img)
  File "/home/permanent/anaconda3/envs/aanet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/permanent/aanet-master/nets/resnet.py", line 181, in forward
    layer3 = self.layer3(layer2)
  File "/home/permanent/anaconda3/envs/aanet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/permanent/anaconda3/envs/aanet/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/permanent/anaconda3/envs/aanet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/permanent/aanet-master/nets/deform.py", line 121, in forward
    out = self.conv2(out)
  File "/home/permanent/anaconda3/envs/aanet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/permanent/aanet-master/nets/deform.py", line 84, in forward
    out = self.deform_conv(x, offset, mask)
  File "/home/permanent/anaconda3/envs/aanet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/permanent/aanet-master/nets/deform_conv/deform_conv.py", line 351, in forward
    self.groups, self.deformable_groups)
  File "/home/permanent/aanet-master/nets/deform_conv/deform_conv.py", line 136, in forward
    raise NotImplementedError
NotImplementedError

this is the error information
please help me

**Comment by haofeixu** [comment]
Deformable conv is supported by GPU only, you should use GPU.
