### ISSUE TITLE
How to use psmnet to make a prediction

### ISSUE THREAD

**Issue by kebinpeng** [haofeixu/aanet#35]
Hi Hello:

I hope everything is OK. I am tring to use the pretrained model of psmnet to make a prediction. But I got some error as shown blow:

Traceback (most recent call last):
  File "predict.py", line 199, in <module>
    main()
  File "predict.py", line 162, in main
    pred_disp = aanet(left, right)[-1]  # [B, H, W]
  File "/usr/local/envs/aanet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/envs/aanet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/envs/aanet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/AANet/nets/aanet.py", line 207, in forward
    left_feature = self.feature_extraction(left_img)
  File "/content/drive/My Drive/AANet/nets/aanet.py", line 136, in feature_extraction
    feature = self.fpn(feature)
  File "/usr/local/envs/aanet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/AANet/nets/feature.py", line 213, in forward
    assert len(self.in_channels) == len(inputs)
AssertionError

Could you give some advises? Any advises is appriciate!

**Comment by kebinpeng** [comment]
I have solved it. sorry.

**Comment by TJUsuchang** [comment]
> I have solved it. sorry.
Hi, I have the same problem as you. Could you give some advises? Any advises is appriciate!
