### ISSUE TITLE
No such file or directory: 'checkpoints/aanet_kittimix/aanet_latest.pth

### ISSUE THREAD

**Issue by yanzhou-li** [haofeixu/aanet#52]
dear author:
i have a trouble when i run the `scripts/aanet_train.sh`,can you tell me some advise
the problem is:
`[2020-11-18 13:53:43,988] => Loading pretrained AANet: checkpoints/aanet_kittimix/aanet_latest.pth`
`Traceback (most recent call last):
  File "train.py", line 243, in <module>
    main()
  File "train.py", line 166, in main
    utils.load_pretrained_net(aanet, args.pretrained_aanet, no_strict=(not args.strict))
  File "/home/liyanzhou/pycharm_project/demo/aanet-master/utils/utils.py", line 77, in load_pretrained_net
    state = torch.load(pretrained_path, map_location='cuda')
  File "/home/liyanzhou/anaconda3/envs/python37/lib/python3.7/site-packages/torch/serialization.py", line 381, in load
    f = open(f, 'rb')
`
`FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/aanet_kittimix/aanet_latest.pth'
`

tks

**Comment by yanzhou-li** [comment]
i solved it!

**Comment by Estrella1024** [comment]
how?
