### ISSUE TITLE
some question about import error

### ISSUE THREAD

**Issue by qqc22111** [haofeixu/aanet#91]
I met the error below when I use the predict.py, can you help me?
Traceback (most recent call last):
  File "D:\Project\BinocularStereoVision\aanet\predict.py", line 10, in <module>
    import nets
  File "D:\Project\BinocularStereoVision\aanet\nets\__init__.py", line 1, in <module>
    from .aanet import AANet
  File "D:\Project\BinocularStereoVision\aanet\nets\aanet.py", line 4, in <module>
    from .feature import (StereoNetFeature, PSMNetFeature, GANetFeature, GCNetFeature,
  File "D:\Project\BinocularStereoVision\aanet\nets\feature.py", line 5, in <module>
    from nets.deform import DeformConv2d
  File "D:\Project\BinocularStereoVision\aanet\nets\deform.py", line 3, in <module>
    from nets.deform_conv import DeformConv, ModulatedDeformConv
  File "D:\Project\BinocularStereoVision\aanet\nets\deform_conv\__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "D:\Project\BinocularStereoVision\aanet\nets\deform_conv\deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda' from partially initialized module 'nets.deform_conv' (most likely due to a circular import) (D:\Project\BinocularStereoVision\aanet\nets\deform_conv\__init__.py)

**Comment by scpaliuhc** [comment]
I met the same problem. Did you solve it?

**Comment by KangriX** [comment]
THE SAME QUESTION. And I failed to install the following package:
`$ bash build.sh
running build_ext
/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/utils/cpp_extension.py:788: UserWarning: The detected CUDA version (11.4) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
building 'deform_conv_cuda' extension
creating /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build
creating /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7
creating /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7/src
Emitting ninja build file /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7/src/deform_conv_cuda.o.d -pthread -B /home/kx/anaconda3/envs/raftstereo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/TH -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/kx/anaconda3/envs/raftstereo/include/python3.7m -c -c /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp -o /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7/src/deform_conv_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7/src/deform_conv_cuda.o 
c++ -MMD -MF /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7/src/deform_conv_cuda.o.d -pthread -B /home/kx/anaconda3/envs/raftstereo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/TH -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/kx/anaconda3/envs/raftstereo/include/python3.7m -c -c /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp -o /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7/src/deform_conv_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp: In function ‘void shape_check(at::Tensor, at::Tensor, at::Tensor*, at::Tensor, int, int, int, int, int, int, int, int, int, int)’:
/home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp:66:3: error: ‘AT_CHECK’ was not declared in this scope; did you mean ‘DCHECK’?
   66 |   AT_CHECK(weight.ndimension() == 4,
      |   ^~~~~~~~
      |   DCHECK
/home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp: In function ‘int deform_conv_forward_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, int)’:
/home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp:194:3: error: ‘AT_CHECK’ was not declared in this scope; did you mean ‘DCHECK’?
  194 |   AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
      |   ^~~~~~~~
      |   DCHECK
/home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp: In function ‘int deform_conv_backward_input_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, int)’:
/home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp:301:3: error: ‘AT_CHECK’ was not declared in this scope; did you mean ‘DCHECK’?
  301 |   AT_CHECK((offset.size(0) == batchSize), 3, "invalid batch size of offset");
      |   ^~~~~~~~
      |   DCHECK
/home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp: In function ‘int deform_conv_backward_parameters_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, float, int)’:
/home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp:417:3: error: ‘AT_CHECK’ was not declared in this scope; did you mean ‘DCHECK’?
  417 |   AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
      |   ^~~~~~~~
      |   DCHECK
/home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp: In function ‘void modulated_deform_conv_cuda_forward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, bool)’:
/home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp:497:3: error: ‘AT_CHECK’ was not declared in this scope; did you mean ‘DCHECK’?
  497 |   AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous");
      |   ^~~~~~~~
      |   DCHECK
/home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp: In function ‘void modulated_deform_conv_cuda_backward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, bool)’:
/home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp:579:3: error: ‘AT_CHECK’ was not declared in this scope; did you mean ‘DCHECK’?
  579 |   AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous");
      |   ^~~~~~~~
      |   DCHECK
[2/2] /usr/local/cuda/bin/nvcc  -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/TH -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/kx/anaconda3/envs/raftstereo/include/python3.7m -c -c /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda_kernel.cu -o /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1746, in _run_ninja_build
    env=env)
  File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
    build_ext.build_extensions(self)
  File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 571, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1424, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension`

**Comment by KangriX** [comment]
> THE SAME QUESTION. And I failed to install the following package: `$ bash build.sh running build_ext /home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/utils/cpp_extension.py:788: UserWarning: The detected CUDA version (11.4) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem. warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda)) building 'deform_conv_cuda' extension creating /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build creating /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7 creating /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7/src Emitting ninja build file /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7/build.ninja... Compiling objects... Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N) [1/2] c++ -MMD -MF /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7/src/deform_conv_cuda.o.d -pthread -B /home/kx/anaconda3/envs/raftstereo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/TH -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/kx/anaconda3/envs/raftstereo/include/python3.7m -c -c /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp -o /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7/src/deform_conv_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14 FAILED: /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7/src/deform_conv_cuda.o c++ -MMD -MF /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7/src/deform_conv_cuda.o.d -pthread -B /home/kx/anaconda3/envs/raftstereo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/TH -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/kx/anaconda3/envs/raftstereo/include/python3.7m -c -c /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp -o /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7/src/deform_conv_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14 cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp: In function ‘void shape_check(at::Tensor, at::Tensor, at::Tensor*, at::Tensor, int, int, int, int, int, int, int, int, int, int)’: /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp:66:3: error: ‘AT_CHECK’ was not declared in this scope; did you mean ‘DCHECK’? 66 | AT_CHECK(weight.ndimension() == 4, | ^~~~~~~~ | DCHECK /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp: In function ‘int deform_conv_forward_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, int)’: /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp:194:3: error: ‘AT_CHECK’ was not declared in this scope; did you mean ‘DCHECK’? 194 | AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset"); | ^~~~~~~~ | DCHECK /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp: In function ‘int deform_conv_backward_input_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, int)’: /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp:301:3: error: ‘AT_CHECK’ was not declared in this scope; did you mean ‘DCHECK’? 301 | AT_CHECK((offset.size(0) == batchSize), 3, "invalid batch size of offset"); | ^~~~~~~~ | DCHECK /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp: In function ‘int deform_conv_backward_parameters_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, float, int)’: /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp:417:3: error: ‘AT_CHECK’ was not declared in this scope; did you mean ‘DCHECK’? 417 | AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset"); | ^~~~~~~~ | DCHECK /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp: In function ‘void modulated_deform_conv_cuda_forward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, bool)’: /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp:497:3: error: ‘AT_CHECK’ was not declared in this scope; did you mean ‘DCHECK’? 497 | AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous"); | ^~~~~~~~ | DCHECK /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp: In function ‘void modulated_deform_conv_cuda_backward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, bool)’: /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda.cpp:579:3: error: ‘AT_CHECK’ was not declared in this scope; did you mean ‘DCHECK’? 579 | AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous"); | ^~~~~~~~ | DCHECK [2/2] /usr/local/cuda/bin/nvcc -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/TH -I/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/kx/anaconda3/envs/raftstereo/include/python3.7m -c -c /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/src/deform_conv_cuda_kernel.cu -o /home/kx/KK/SDE/modelZoo/aanet/nets/deform_conv/build/temp.linux-x86_64-3.7/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14 ninja: build stopped: subcommand failed. Traceback (most recent call last): File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1746, in _run_ninja_build env=env) File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/subprocess.py", line 512, in run output=stdout, stderr=stderr) subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "setup.py", line 12, in cmdclass={'build_ext': BuildExtension}) File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/setuptools/**init**.py", line 153, in setup return distutils.core.setup(**attrs) File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/distutils/core.py", line 148, in setup dist.run_commands() File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/distutils/dist.py", line 966, in run_commands self.run_command(cmd) File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/distutils/dist.py", line 985, in run_command cmd_obj.run() File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run _build_ext.run(self) File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/distutils/command/build_ext.py", line 340, in run self.build_extensions() File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions build_ext.build_extensions(self) File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions self._build_extensions_serial() File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial self.build_extension(ext) File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension _build_ext.build_extension(self, ext) File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension depends=ext.depends) File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 571, in unix_wrap_ninja_compile with_cuda=with_cuda) File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1424, in _write_ninja_file_and_compile_objects error_prefix='Error compiling objects for extension') File "/home/kx/anaconda3/envs/raftstereo/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build raise RuntimeError(message) from e RuntimeError: Error compiling objects for extension`

it's caused by mismatch version of torch. fixed by replacing all "AT_CHECK" with "TORCH_CHECK"
